### PR TITLE
Handle more than one flag passed after description in rspec DSL methods.

### LINKED ISSUE #221: "Rubyfmt failed to correctly deserialize a tree from ripper" in concurrent-ruby gem
Hello again! After [my previous issue report](https://github.com/penelopezone/rubyfmt/issues/220) I decided to try `rubyfmt` with a few other Ruby gems that I had checked out locally.

`rubyfmt` fails to process multiple files from `concurrent-ruby`.

* Ruby version: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`
* Rubyfmt git sha: https://github.com/penelopezone/rubyfmt/releases/tag/v0.3.1

## Input file

All of these fail:

* file was: docs-source/actor/messaging.in.rb
* file was: docs-source/actor/messaging.out.rb
* file was: examples/a-tour-of-go-channels/buffered-channels.rb
* file was: examples/a-tour-of-go-channels/channels.rb
* file was: examples/a-tour-of-go-channels/equivalent-binary-trees.rb
* file was: examples/a-tour-of-go-channels/select.rb
* file was: examples/go-by-example-channels/channel-directions.rb
* file was: examples/go-by-example-channels/channel-synchronization.rb
* file was: examples/go-by-example-channels/closing-channels.rb
* file was: examples/go-by-example-channels/rate-limiting.rb
* file was: examples/go-by-example-channels/timers.rb
* file was: examples/go-by-example-channels/worker-pools.rb
* file was: lib/concurrent-ruby/concurrent/collection/map/atomic_reference_map_backend.rb
* file was: lib/concurrent-ruby/concurrent/thread_safe/util/striped64.rb
* file was: spec/concurrent/atomic/count_down_latch_spec.rb
* file was: spec/concurrent/atomic/cyclic_barrier_spec.rb
* file was: spec/concurrent/atomic/event_spec.rb
* file was: spec/concurrent/mvar_spec.rb
* file was: tmp/x86_64-linux/stage/lib/concurrent/atomic_reference/direct_update.rb

Link to concurrent-ruby repository: https://github.com/ruby-concurrency/concurrent-ruby

## Rubyfmt's output

(None)

## This breaks because

Does not work ;)

### PR DESCRIPTION
**Pull request by phiggins**
Followup to #283.
This is the last PR needed to close #221.

This ended up being more involved than I expected because `format_assocs` was written expecting there was a breakable on the breakable stack, and in the single line case this wasn't true.

I might have been able to fix this by wrapping the initial divergence in a breakable, in the top branch of this code, but it seemed like a deliberate choice not to do that: https://github.com/phiggins/rubyfmt/blob/81b710e8f86a7b466ecdff410581347da66fa79a/librubyfmt/src/format.rs#L2292-L2297

@penelopezone do you have thoughts on this one?

### CODE REVIEW

**Comment by phiggins** [comment]
I added another commit that breaks things into smaller functions. I like it, I think, but I'm not convinced this is a clear win. :thinking:

File: librubyfmt/src/format.rs [hunk 1]
```diff
@@ -852,42 +852,57 @@ pub fn format_assocs(
...
-                    }
-                    format_expression(ps, new.2);
-                }
-                AssocNewOrAssocSplat::AssocSplat(splat) => {
-                    ps.emit_ident("**".to_string());
-                    format_expression(ps, splat.1);
-                }
-            }),
-        );
+        ps.emit_soft_indent();
```
Comment (fables-tales) [inline librubyfmt/src/format.rs:855]: does this need the special case?

Comment (phiggins) [reply librubyfmt/src/format.rs:855]: No, since that was only necessary for one scenario I pushed that to the caller to remove a conditional: https://github.com/penelopezone/rubyfmt/pull/285/files#diff-63b92541cacb647f9227c6eac250e906cb60dade9a39a892517f2d99ec122a28R694
