### PR TITLE
Fix :kwrest_param

### LINKED ISSUE #36: Breaks on double-splat in method signature
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: cbc2e0edd23af6abc63659bd654e5580c4521571

## Input file

```ruby
def foo(a, **b)
end
```

## Rubyfmt's output

```
Traceback (most recent call last):
  8: from ../rubyfmt/src/rubyfmt.rb:2285:in `<main>'
  7: from ../rubyfmt/src/rubyfmt.rb:2282:in `main'
  6: from ../rubyfmt/src/rubyfmt.rb:2142:in `format_program'
  5: from ../rubyfmt/src/rubyfmt.rb:2142:in `each'
  4: from ../rubyfmt/src/rubyfmt.rb:2143:in `block in format_program'
  3: from ../rubyfmt/src/rubyfmt.rb:2136:in `format_expression'
  2: from ../rubyfmt/src/rubyfmt.rb:2057:in `block in format_expression'
  1: from ../rubyfmt/src/rubyfmt.rb:462:in `format_def'
../rubyfmt/src/rubyfmt.rb:558:in `format_params': dont know how to deal with a params list (RuntimeError)
```

## This breaks because

Fill out this section with what Rubyfmt should have done.

### PR DESCRIPTION
**Pull request by bquorning**
Fixes #36 

E.g. on this file would raise an exception:
```rb
def foo(a, **b)
end
```

### CODE REVIEW

File: src/rubyfmt.rb [hunk 1]
```diff
@@ -584,7 +598,7 @@ def format_params(ps, params, open_delim, close_delim)
     ps.emit_ident(open_delim)
   end
 
-  bad_params = params[6..-1].any? { |x| !x.nil? }
+  bad_params = params[7..-1].any? { |x| !x.nil? }
```
Comment (bquorning) [inline src/rubyfmt.rb]: I am not sure if this line makes sense anymore? Can there be more than 8 elements in `params`?

**Comment by samphippen** [comment]
Ran CI locally.
