### PR TITLE
Fix multiline rescue exception formatting (#356)

### LINKED ISSUE #356: A long `rescue` line or multiline `rescue` with multiple errors is formatted to be a single long line
* Ruby version: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]
* Rubyfmt git sha: 1a40d19a4117a18bdd8b29bc15d5a3d107600dba (but used https://github.com/penelopezone/rubyfmt/pull/350)

## Input file

```ruby
begin

rescue OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError => exception

end

begin
rescue OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError => exception
end
```

## Rubyfmt's output

```ruby
begin

rescue OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError => exception
end

begin
rescue OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError, OpenSSL::SSL::SSLError => exception
end
```

## This breaks because it

I don't want a single long line. I'd expect rubyfmt to do something similar to this:
```ruby
begin

rescue OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError => exception
end

begin
rescue OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError,
       OpenSSL::SSL::SSLError => exception
end

```

### PR DESCRIPTION
**Pull request by fables-tales**
When rescue has many exception types that exceed the line length, format them across multiple lines with proper indentation:

  rescue OpenSSL::SSL::SSLError,
    OpenSSL::SSL::SSLError,
    OpenSSL::SSL::SSLError => exception

Short lists still stay on one line: rescue A, B, C => e

### CODE REVIEW

File: fixtures/small/rescue_multiline_exceptions_actual.rb [hunk 1]
```diff
@@ -0,0 +1,26 @@
+begin
+rescue OpenSSL::SSL::SSLError,
```
Comment (reese) [inline fixtures/small/rescue_multiline_exceptions_actual.rb:2]: Might also be nice to have a single-line, >120 character fixture as well

**Review by reese — APPROVED** [review]
